# Generated by Django 5.0.2 on 2024-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverPhoto',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover_images'),
        ),
    ]
